# Generated by Django 5.2.7 on 2025-10-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_licensed',
            new_name='isLicensed',
        ),
    ]
