# Generated by Django 5.2.7 on 2025-10-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_licensed_user_islicensed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isLicensed',
            new_name='is_licensed',
        ),
    ]
