# Generated by Django 5.2.7 on 2025-10-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_islicensed_user_is_licensed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('TC', 'Teacher'), ('ST', 'Student'), ('SA', 'Super Admin')], max_length=2),
        ),
    ]
