# Generated by Django 5.2.7 on 2025-10-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_licensed',
            new_name='isLicensed',
        ),
    ]
