# Generated by Django 5.2.7 on 2025-10-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_islicensed_user_is_licensed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.school'),
        ),
    ]
