# Generated by Django 5.2.7 on 2025-10-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_announcement_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.CharField(auto_created=True, max_length=36, primary_key=True, serialize=False),
        ),
    ]
