# Generated by Django 5.2.7 on 2025-10-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_announcement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='number_of_teachers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.CharField(auto_created=True, max_length=36, primary_key=True, serialize=False),
        ),
    ]
