# Generated by Django 5.2.7 on 2025-10-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_competition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled')], default='pending', max_length=16),
        ),
    ]
