# Generated by Django 5.2.7 on 2025-11-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_competition_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participants',
            new_name='participant',
        ),
    ]
