# Generated by Django 5.2.7 on 2025-11-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_participants_conversation_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participant',
            new_name='participants',
        ),
    ]
